spring:
  application:
    name: auth-service
  cloud:
    config:
      name: auth, commons
  config:
    import: "configserver:http://localhost:8123"
  profiles:
    active: dev
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
