spring:
  application:
    name: cloud-gateway
  config:
    name: cloud-gateway
    import: "configserver:http://localhost:8123"
  main:
    web-application-type: reactive
  profiles:
    active: dev
logging:
  level:
    org.springframework.cloud.config: DEBUG