spring:
  application:
    name: cloud-gateway
  config:
    name: cloud-gateway
    import: "configserver:http://localhost:8123"
  main:
    web-application-type: reactive
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: restart,health,info
  endpoint:
    restart:
      enabled: true
#springdoc:
#  swagger-ui:
#    use-root-path: true