version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.12-management  # Use the management version for easier debugging
    container_name: rabbitmq_stomp
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_PLUGINS: "rabbitmq_stomp"
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
      - "61613:61613" # STOMP port
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_stomp && rabbitmq-server"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025 # smtp port
      - 8025:8025 # web ui port

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mail_service_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

# Define volumes at root level
volumes:
  mongodb_data: {}  # {} means using default driver options