version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.12-management  # Use the management version for easier debugging
    container_name: rabbitmq_stomp
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_PLUGINS: "rabbitmq_stomp"
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
      - "61613:61613" # STOMP port
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_stomp && rabbitmq-server"
