spring:
  application:
    name: messages-websocket
  cloud:
    config:
      name: messages-websocket, commons
  config:
    import: "configserver:http://localhost:8123"
  profiles:
    active: dev
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.websocket: DEBUG