spring:
  application:
    name: messages-websocket
  cloud:
    config:
      name: messages-websocket, commons
  config:
    import: "configserver:http://localhost:8123"
  profiles:
    active: dev
  main:
    web-application-type: reactive