spring:
  application:
    name: chat-messages
  cloud:
    config:
      name: commons, chat-messages
  config:
    import: "configserver:http://localhost:8123"
  profiles:
    active: dev
  main:
    web-application-type: reactive