spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/chat_service_database?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9997
  forward-headers-strategy: framework
logging:
  level:
    org:
      asi: debug