server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          search-locations: D:\springboot\spring-micro-websocket-chat-config\files
  profiles:
    active: native