server:
  port: 8123
spring:
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:///D:/springboot/chat-app-micro-config/files
            - file:///D:/springboot/chat-app-micro-config/files/service/commons
            - file:///D:/springboot/chat-app-micro-config/files/service/auth-service
            - file:///D:/springboot/chat-app-micro-config/files/service/chat-messages-service
            - file:///D:/springboot/chat-app-micro-config/files/service/messages-websocket-service
  profiles:
    active: native, dev
logging:
  level:
    org.springframework.cloud.config: DEBUG